[package]
name = "jalali-date"
version = "0.2.0"
edition = "2021"
license = "MIT"
description = "Convert Date To Jalali"
repository = "https://github.com/mohammadjavad948/jalali_date"
keywords = ["date", "jalali-date"]

[dependencies]
